/**
 * Writes src/lib/route.ts: the official round (public/gpx/<gpxFile>) thinned to a point every
 * ~50 m, for the "follows the route" check. Run after replacing the route GPX:
 *   npm run route
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { ROUNDS } from '../src/lib/config.ts';
import { haversineKm, parsePoints } from '../src/lib/gpx.ts';

const file = new URL(`../public/gpx/${ROUNDS.long.gpxFile}`, import.meta.url);
const pts = parsePoints(readFileSync(file, 'utf8'));
const out = [pts[0]];
for (const p of pts.slice(1)) if (haversineKm(out[out.length - 1], p) >= 0.05) out.push(p);
if (out[out.length - 1] !== pts[pts.length - 1]) out.push(pts[pts.length - 1]);

const body = out.map((p) => `[${p.lat.toFixed(5)},${p.lon.toFixed(5)}]`).join(',');
writeFileSync(
  new URL('../src/lib/route.ts', import.meta.url),
  `/** Generated by scripts/make-route.ts from public/gpx/${ROUNDS.long.gpxFile}. Don't edit by hand: run \`npm run route\`. */
/** The official round as [lat, lon] pairs, about every 50 m, in the direction it is walked. */
export const ROUTE_LINE: [number, number][] = [${body}];
`,
);
console.log(`Wrote src/lib/route.ts (${out.length} points from ${pts.length})`);
