/**
 * Writes src/lib/route.ts: every point of the official round (public/gpx/<gpxFile>), used to build
 * realistic test tracks. Run after replacing the route GPX:
 *   npm run route
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { ROUNDS } from '../src/lib/config.ts';
import { haversineKm, parsePoints } from '../src/lib/gpx.ts';

const file = new URL(`../public/gpx/${ROUNDS.long.gpxFile}`, import.meta.url);
const pts = parsePoints(readFileSync(file, 'utf8'));
// Drop exact repeats only: thinning would cut corners such as the turn at Mosedale Cottage.
const out = pts.filter((p, i) => i === 0 || haversineKm(pts[i - 1], p) > 0.001);

const body = out.map((p) => `[${p.lat.toFixed(5)},${p.lon.toFixed(5)}]`).join(',');
writeFileSync(
  new URL('../src/lib/route.ts', import.meta.url),
  `/** Generated by scripts/make-route.ts from public/gpx/${ROUNDS.long.gpxFile}. Don't edit by hand: run \`npm run route\`. */
/** The official round as [lat, lon] pairs, in the direction it is walked. */
export const ROUTE_LINE: [number, number][] = [${body}];
`,
);
console.log(`Wrote src/lib/route.ts (${out.length} points from ${pts.length})`);
